version: "3"

services:
  db:
    image: bitnami/mariadb:10.6
    volumes:
      - ./db/sql-init:/docker-entrypoint-initdb.d
      - db_data:/bitnami/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: mapsdb

  redis:
    image: redis:6.2-bullseye
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/var/lib/redis

  public:
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    build: ./public

volumes:
  db_data:
  redis_data:
