version: "3"

services:
  db:
    image: bitnami/mariadb:10.6
    volumes:
      - ./db/sql-init:/docker-entrypoint-initdb.d
      - db_data:/bitnami/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASS}
      MARIADB_DATABASE: mapsdb

  redis:
    image: redis:6.2-bullseye
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/var/lib/redis

  public:
    env_file:
      - .env
      - .env.dockerconfig
    depends_on:
      - db
      - redis
    build: ./public

  maps:
    env_file:
      - .env
      - .env.dockerconfig
    depends_on:
      - db
      - redis
    build: ./maps

volumes:
  db_data:
  redis_data:
