version: "3"

# Expose ports for debugging

services:
  db:
    ports:
      - 58801:3306

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    depends_on:
      - db
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 58802:80

  redis:
    ports:
      - 58803:6379

  public:
    build:
      dockerfile: Dockerfile.local
    volumes:
      - ./public:/usr/app
      - /usr/app/node_modules
    ports:
      - 58804:3001
      - 9229:9229
