version: "3"

services:
  db:
    image: mariadb
    volumes:
      - ./db/sql-init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: mapsdb

  redis:
    image: redis:bullseye
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - redis_data:/var/lib/redis

  public:
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    build: ./public
    ports:
      - 3001:3001

volumes:
  db_data:
  redis_data:
